name: update runs issue

on:
  schedule:
    - cron: "0/30 * * * *"
  push:
  pull_request:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: update report
        run: |
          set -x
          hub issue show 2 > issue
          cat issue
          sed -i '/^\*/d' issue
          cat issue
          sed -i '1,1s/^# //' issue
          cat issue
          echo "- [ ] [$GITHUB_RUN_ID $(date)]($GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID)" >> issue
          cat issue
          hub issue update 2 -F issue
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




